### ISSUE TITLE
install-modules.ps1 prompts twice for credentials

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/Sitecore.HabitatHome.Utilities#56]
Prompts once for SAT and once for other modules.
Need to change to prompt only once.

Aha! Link: https://habitathome.aha.io/features/INSTALL-3

**Comment by rroman81** [comment]
Saw that issue as well on my install.

**Comment by jeanfrancoislarente** [comment]
Should be fixed now (develop branch)
