### ISSUE TITLE
warmup.ps1 fails to login

### ISSUE THREAD

**Issue by GlennvG** [Sitecore/Sitecore.HabitatHome.Utilities#68]
Trying to use the warmup.ps1 script. But login fails with message username is required.

Invoke-WebRequest : Server Error in '/' Application.
Empty strings are not allowed.
Parameter name: username
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about
the error and where it originated in the code.
Exception Details: System.ArgumentException: Empty strings are not allowed.
Parameter name: username

Aha! Link: https://habitathome.aha.io/features/INSTALL-2

**Comment by jeanfrancoislarente** [comment]
@GlennvG 
Is this on 9.0.2 or 9.1?

9.1 now uses IdentityServer and we haven't had a chance to take a look at authenticating the warmup script against IdentityServer.

**Comment by GlennvG** [comment]
@jeanfrancoislarente i'm using 9.0.2.

**Comment by jeanfrancoislarente** [comment]
Are you using release/9.0.2 branch of repo?

https://github.com/Sitecore/Sitecore.HabitatHome.Utilities/tree/release/9.0.2

**Comment by jeanfrancoislarente** [comment]
Resolved with #85
