### ISSUE TITLE
Change warmup script to use SIF

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Sitecore/Sitecore.HabitatHome.Utilities#69]
Work started in SHA e14328a524ae22c43108c105b62a477e19ac7f5b

Need to add a client to Identity Server Host XML

Can add the following to the Clients section (`<identityserverroot>\Config\production\Sitecore.IdentityServer.Host.xml`)

`<PostmanClient>
          <ClientId>postman-api</ClientId>
          <ClientName>postman-api</ClientName>
          <AccessTokenType>0</AccessTokenType>
          <AllowOfflineAccess>true</AllowOfflineAccess>
          <AlwaysIncludeUserClaimsInIdToken>false</AlwaysIncludeUserClaimsInIdToken>
          <AccessTokenLifetimeInSeconds>3600</AccessTokenLifetimeInSeconds>
          <IdentityTokenLifetimeInSeconds>3600</IdentityTokenLifetimeInSeconds>
          <AllowAccessTokensViaBrowser>true</AllowAccessTokensViaBrowser>
          <RequireConsent>false</RequireConsent>
          <RequireClientSecret>true</RequireClientSecret>
          <AllowedGrantTypes>
            <AllowedGrantType1>password</AllowedGrantType1>
          </AllowedGrantTypes>
          <AllowedCorsOrigins>
          </AllowedCorsOrigins>
          <AllowedScopes>
            <AllowedScope1>openid</AllowedScope1>
            <AllowedScope2>sitecore.profile</AllowedScope2>
            <AllowedScope3>sitecore.profile.api</AllowedScope3>
          </AllowedScopes>
          <ClientSecrets>
            <ClientSecret1>ClientSecret</ClientSecret1>
          </ClientSecrets>
          <UpdateAccessTokenClaimsOnRefresh>false</UpdateAccessTokenClaimsOnRefresh>
        </PostmanClient>
`

Current issue is a 500 AntiForgery error when accessing /sitecore pages.

> A claim of type ' [http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier](http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier)' or ' [http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider](http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider)' was not present on the provided ClaimsIdentity. To enable anti-forgery token support with claims-based authentication, please verify that the configured claims provider is providing both of these claims on the ClaimsIdentity instances it generates. If the configured claims provider instead uses a different claim type as a unique identifier, it can be configured by setting the static property AntiForgeryConfig.UniqueClaimTypeIdentifier.

Aha! Link: https://habitathome.aha.io/features/INSTALL-1

**Comment by dnstommy** [comment]
@jeanfrancoislarente I just got back a response from Sitecore on how to use Bearer tokens in Sitecore (not commerce). Check out my answer here. (https://sitecore.stackexchange.com/questions/15711/jwt-tokens-for-authentication-for-9-1/16232#16232) I think if you use the SitecorePassword client_id you will have a valid token to use. The token from `postman-api` only works for the commerce server implementation of Identity server, from what I understand.
