### ISSUE TITLE
How to Install HabitatHome module after XP installation is completed?

### ISSUE THREAD

**Issue by eugentorica** [Sitecore/Sitecore.HabitatHome.Utilities#86]
Hi,

What is the reason of habitathome module is commended in install_modules.ps1?
I saw also that install_habitathome.ps1 file was renamed to install_habitathome.ps1.donotuse.
Is there a way to install habitathome module on a machine that has XP environment with other modules installed?

Thank you in advance.

**Comment by jeanfrancoislarente** [comment]
The install habitat home functionality is still not complete. The current approach to installing Habitat Home is deploying it by cloning the Sitecore.HabitatHome..Platform repo and running .\build.ps1

Habitat Home will then get deployed and items sync'ed using Unicorn, the way it has been for a while.

We are still working on the WDP installation of Habitat Home and will update the README file(s) when appropriate.
